heat_template_version: 2015-10-15

description: Static server cluster (N nodes) fragment

parameters:
  network:
    type: string
  network01_prefix:
    type: string
  network_port_security_enabled:
    type: boolean
    default: false
  instance_count:
    type: string
  instance_count:
    type: string
  instance_name:
    type: string
  instance_domain:
    type: string
  instance_cluster:
    type: string
  instance_zone:
    type: string
  instance_os:
    type: string
  instance_flavor:
    type: string
  instance_image:
    type: string
  instance_boot_timeout:
    type: number
    default: 3600
  instance_cloud_init:
    type: string
    default: ""
  volume_size:
    type: number
    default: 20
  key_pair:
    type: string
    default: mcp-scale-jenkins

resources:
  server_test:
    type: OS::Heat::ResourceGroup
    properties:
      count: { get_param: instance_count }
      removal_policies: [{'resource_list': ['0']}]
      resource_def:
        type: MCP::ClusterMember
        properties:
          key_pair: { get_param: key_pair }
          network: { get_param: network }
          network_port_security_enabled: { get_param: network_port_security_enabled }
          network01_prefix: { get_param: network01_prefix }
          instance_name: { list_join: ['', [
            { get_param: instance_name },
            "%index%"
          ]]}
          instance_domain: { get_param: instance_domain }
          instance_cluster: { get_param: instance_cluster }
          instance_zone:  { get_param: instance_zone }
          instance_os: { get_param: instance_os }
          instance_flavor: { get_param: instance_flavor }
          instance_image: { get_param: instance_image }
          instance_boot_timeout: { get_param: instance_boot_timeout }
          instance_cloud_init: { get_param: instance_cloud_init }
          volume_size: { get_param: volume_size }
          affinity_group: { get_resource: anti-affinity_group }
  anti-affinity_group:
   type: OS::Nova::ServerGroup
   properties:
    name: hosts on separate compute nodes
    policies:
     - anti-affinity
